### PR TITLE
Upgrade to rails 4 and sqlite

### PR DESCRIPTION
**Pull request by drusepth**
Opening pull request into `migrate-to-sql` branch (rather than master) so I can better work with the changes RE the data migration from mongo to sqlite. Getting closer.

### CODE REVIEW

**Comment by drusepth** [comment]
I'm yolomerging this into `migrate-to-sql` because I can't check out your `Cantido:sqlrails4` branch for some reason.

**Comment by drusepth** [comment]
In the process of rebasing thanks to @euank's wonderful help. Merge conflicts everywhere, but it's something to work through. Progress!

**Comment by Cantido** [comment]
I will see what I can do. I tried once a while ago, but since a lot of the web files have completely changed location, merge tools don't do it right. Even manually resolving every conflict didn't get it quite right, so I'm not sure how a rebase can be done. If I remember correctly, I just generated a new Rails 4 project and dragged the files into the right place.

**Comment by drusepth** [comment]
I believe I merged this properly. 

The server runs, seems to work fine, rails is 4.1, it's using postgres instead of mongoDB, and the last commit in `git log` is your https://github.com/Cantido/Indent/commit/623115e7b860d6ddb47556dc89b5f065a0c14a85.

Closing this pull request, but it has been manually merged into branch `sqlite4`.

@Cantido Are these the test results you expect?

untitled

**Comment by Cantido** [comment]
Yes! That test was intended to fail until we merged the fix for #366. I wrote a Capybara test to log out and then log back in to trigger it. This is so exciting! I think updating to Rails 4 & SQL was the big hump. You've done a lot of work in the time after I forked, but I think merging those would be a much less serious effort than this one.

I'm sorry to have caused you such a huge pile of work!

**Comment by drusepth** [comment]
Haha, no worries, I'm sorry it took so long. This was a big hump indeed, but I agree it was the right thing to do. It is indeed exciting, especially now that this blocker is cleared up! I have a ton I've been wanting to do and hope to get to them soon. :)

**Comment by drusepth** [comment]
Update on this, there was some git wonkiness that caused the old UI to come back, but I resolved it (for the most part) by reverting https://github.com/drusepth/Indent/commit/6f8ae925ba5d844b180abe691961f41b9e30f765. This seemed to bring in all the new UI and other changes that had been made on master, but seems to have mixed some old bugs in that existed in the old UI (e.g. #222). I'm taking a look at this now.

**Comment by drusepth** [comment]
Closing in favor of https://github.com/drusepth/Indent/pull/410

**Pull request closed without merging**
