### PR TITLE
Merge SQLite + Rails 4 into master!

### PR DESCRIPTION
**Pull request by drusepth**
Remaining issues:

- [x] UI seems to be a mixture of old and new
- [x] Fonticons aren't working (#222)
- [x] Failing tests

### CODE REVIEW

**Comment by drusepth** [comment]
@Cantido I think everything is fixed up except the two remaining test failures. I took a look at them but I'm not familiar enough with Capybara to make much progress. It looks like the `test_helper.rb` IntegrationTest functions aren't actually hitting the controller, and therefore aren't creating users or logging them in properly.

Would you be able to take a look at those two tests, since it seems to be a test issue? Registering and logging in seems to work just fine from the UI.

```
drusepth@tab:~/Indent$ rake test
[Coveralls] Using SimpleCov's 'rails' settings.
Run options: --seed 48896

# Running:

.....................F.F..........................

Finished in 1.372899s, 36.4193 runs/s, 66.2831 assertions/s.

  1) Failure:
UserStoriesTest#test_creating_a_new_user_ends_at_the_new_user's_dashboard [/home/drusepth/Indent/test/integration/user_stories_test.rb:8]:
New user was not directed to their dashboard after creating an account.
Expected: "/my/content"
  Actual: "/register"


  2) Failure:
UserStoriesTest#test_logging_in_as_an_existing_user_goes_to_the_users_dashboard [/home/drusepth/Indent/test/integration/user_stories_test.rb:14]:
Existing user was not directed to their dashboard after logging in.
Expected: "/my/content"
  Actual: "/login"

50 runs, 91 assertions, 2 failures, 0 errors, 0 skips
drusepth@tab:~/Indent$ 
```

**Comment by drusepth** [comment]
Scratch that, it _is_ awesome to see all green tests. The tests all pass, the site looks relatively stable, and we look fully upgraded.

@Cantido Is there anything else you'd like to see done before I merge this into master and prepare for a production release?

**Comment by Cantido** [comment]
Nope! if all the tests pass and it looks good, then we're set! I'm so happy to see that big green button.

**Comment by Cantido** [comment]
Just to confirm, we're waiting for [the main site](http://indentapp.com) to finish the domain transfer, before we merge?

**Comment by drusepth** [comment]
We were waiting on me to actually do it, I believe. Doing it now! (#380)

Database successfully converted over, now merging this into master so we can get it up on prod before the site comes back up tomorrow! Yay for multi-tasking downtime!

**Comment by Cantido** [comment]
I am gonna write SO MANY FUNCTIONAL TESTS

**Pull request merged**
